{
  "formatVersion": "1.1",
  "component": {
    "group": "net.tonimatasdev",
    "module": "devlib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "devlib-1.0.0.jar",
          "url": "devlib-1.0.0.jar",
          "size": 53443,
          "sha512": "22683a805a040082835cc7738e1bde3e370f57663ba2aad14059da14c863e6c160ab17e33ec8dfa8254853fcc3de2a1bcce66ad88cad1693ff9bd57a00c3a766",
          "sha256": "b8623930bf3ce85b4c86b9d5d64b10b88f9c014e31d7b7cda078fa2d7b036e08",
          "sha1": "683be27c57e5cf0f266526dc6151d31cbf9c4a26",
          "md5": "552cb271e87bddc8892f2832d19b0e0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "devlib-1.0.0.jar",
          "url": "devlib-1.0.0.jar",
          "size": 53443,
          "sha512": "22683a805a040082835cc7738e1bde3e370f57663ba2aad14059da14c863e6c160ab17e33ec8dfa8254853fcc3de2a1bcce66ad88cad1693ff9bd57a00c3a766",
          "sha256": "b8623930bf3ce85b4c86b9d5d64b10b88f9c014e31d7b7cda078fa2d7b036e08",
          "sha1": "683be27c57e5cf0f266526dc6151d31cbf9c4a26",
          "md5": "552cb271e87bddc8892f2832d19b0e0c"
        }
      ]
    }
  ]
}
