{
  "formatVersion": "1.1",
  "component": {
    "group": "net.tonimatasdev",
    "module": "devlib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "devlib-1.0.0.jar",
          "url": "devlib-1.0.0.jar",
          "size": 53380,
          "sha512": "74e222afc4134dd084566bc4d4671571790708ae950f36dfda2cdbb102381e06edb7c5d213b7c7caaf38b9559d41bf6635ab3de2562826d98f7f8ecc770d2b92",
          "sha256": "413589f8001b5b1858289defe87372b283d3a8acf1fce9003ed0ac4cf6089643",
          "sha1": "c450de40d855fa11ad2437b18d3eb4834e355284",
          "md5": "47b52a1fdc49f4b498ffb60e1f49527f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "devlib-1.0.0.jar",
          "url": "devlib-1.0.0.jar",
          "size": 53380,
          "sha512": "74e222afc4134dd084566bc4d4671571790708ae950f36dfda2cdbb102381e06edb7c5d213b7c7caaf38b9559d41bf6635ab3de2562826d98f7f8ecc770d2b92",
          "sha256": "413589f8001b5b1858289defe87372b283d3a8acf1fce9003ed0ac4cf6089643",
          "sha1": "c450de40d855fa11ad2437b18d3eb4834e355284",
          "md5": "47b52a1fdc49f4b498ffb60e1f49527f"
        }
      ]
    }
  ]
}
