{
  "formatVersion": "1.1",
  "component": {
    "group": "net.tonimatasdev",
    "module": "devlib",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "devlib-1.0.1.jar",
          "url": "devlib-1.0.1.jar",
          "size": 59782,
          "sha512": "b29e0af81ead2e02d9bc79b0a0d64b393e54d2e023b45468eddbb89f60476352eb4fa6bb0ca8fba509e78fede93b232577164c8bb72cc884d8c3b57a501307b9",
          "sha256": "5a94341746b93908caf79feb40730b88bb37a5221f77c8796dec794cfa18b109",
          "sha1": "eef194b8fa21f7a0f755f5aba92f601a119bc573",
          "md5": "60ccbad4c211e3d11fc269597d975c63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "devlib-1.0.1.jar",
          "url": "devlib-1.0.1.jar",
          "size": 59782,
          "sha512": "b29e0af81ead2e02d9bc79b0a0d64b393e54d2e023b45468eddbb89f60476352eb4fa6bb0ca8fba509e78fede93b232577164c8bb72cc884d8c3b57a501307b9",
          "sha256": "5a94341746b93908caf79feb40730b88bb37a5221f77c8796dec794cfa18b109",
          "sha1": "eef194b8fa21f7a0f755f5aba92f601a119bc573",
          "md5": "60ccbad4c211e3d11fc269597d975c63"
        }
      ]
    }
  ]
}
